// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID     string   `json:"id"`
	Size   int      `json:"size"`
	Start  *Point   `json:"start"`
	Target *Point   `json:"target"`
	Path   []*Point `json:"path"`
}

type NewBoard struct {
	Size   int       `json:"size"`
	Start  *NewPoint `json:"start"`
	Target *NewPoint `json:"target"`
}

type NewPoint struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Point struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type UpdateBoard struct {
	ID     string    `json:"id"`
	Size   *int      `json:"size"`
	Start  *NewPoint `json:"start"`
	Target *NewPoint `json:"target"`
}

type UpdatePoint struct {
	X *int `json:"x"`
	Y *int `json:"y"`
}
